# .readthedocs.yaml
version: 2

# Set the version of Python and other tools you might need
build:
  os: "ubuntu-22.04"
  tools:
    python: "3.10"
  jobs:
    post_create_environment:
      - pip install poetry
      - poetry config virtualenvs.create false
    post_install:
      - poetry install --only docs

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py